export const FORMS = [
  // ─── 1. Egg Production ────────────────────────────────
  {
    title: "Egg Production",
    api: "eggproduction",
    fields: [
      {
        name: "shed_no",
        label: "Shed",
        type: "dropdown_api",
        apiSource: "sheds",
        labelKey: "SHED_NAME",
        valueKey: "SHED_NAME",
        required: true,
      },
      {
        name: "flock_no",
        label: "Flock",
        type: "dropdown_api",
        apiSource: "flocksByShed",
        labelKey: "FLOCK_NAME",
        valueKey: "FLOCK_NAME",
        dependsOn: "shed_no",
        required: true,
      },
      {
        name: "production_date",
        label: "Production Date",
        type: "date",
        required: true,
      },
      {
        name: "transaction_type",
        label: "Transaction Type",
        type: "dropdown_api",
        apiSource: "eggTransactions",
        labelKey: "TRANSACTION_TYPE",
        valueKey: "TRANSACTION_TYPE",
        required: true,
      },
      {
        name: "egg_type",
        label: "Egg Type",
        type: "dropdown_api",
        apiSource: "eggTypes",
        labelKey: "EGG_TYPE",
        valueKey: "EGG_TYPE",
        required: true,
      },
      { name: "egg_count", label: "Egg Count", type: "number", required: true },
      { name: "comments", label: "Comments", type: "text", required: true },
    ],
  },

  // ─── 2. Bird Live Stock ───────────────────────────────
  {
    title: "Bird Live Stock",
    api: "birdLiveStock",
    fields: [
      {
        name: "shed_no",
        label: "Shed",
        type: "dropdown_api",
        apiSource: "sheds",
        labelKey: "SHED_NAME",
        valueKey: "SHED_NAME",
        required: true,
      },
      {
        name: "flock_no",
        label: "Flock",
        type: "dropdown_api",
        apiSource: "flocksByShed",
        labelKey: "FLOCK_NAME",
        valueKey: "FLOCK_NAME",
        dependsOn: "shed_no",
        required: true,
      },
      {
        name: "reporting_date",
        label: "Reporting Date",
        type: "date",
        required: true,
      },
      {
        name: "loss_of_bird",
        label: "Loss Of Bird",
        type: "number",
        required: true,
      },
      {
        name: "loss_type",
        label: "Loss Type",
        type: "dropdown_api",
        apiSource: "birdLossTypes",
        labelKey: "LOSS_TYPE",
        valueKey: "LOSS_TYPE",
        required: true,
      },
      { name: "comments", label: "Comments", type: "text", required: true },
    ],
  },

  // ─── 3. Egg Godown Stock ──────────────────────────────
  {
    title: "Egg Godown Stock",
    api: "eggGodownStock",
    fields: [
      {
        name: "shed_no",
        label: "Shed",
        type: "dropdown_api",
        apiSource: "sheds",
        labelKey: "SHED_NAME",
        valueKey: "SHED_NAME",
        required: true,
      },
      {
        name: "flock_no",
        label: "Flock",
        type: "dropdown_api",
        apiSource: "flocksByShed",
        labelKey: "FLOCK_NAME",
        valueKey: "FLOCK_NAME",
        dependsOn: "shed_no",
        required: true,
      },
      {
        name: "production_date",
        label: "Production Date",
        type: "date",
        required: true,
      },
      {
        name: "egg_type",
        label: "Egg Type",
        type: "dropdown_api",
        apiSource: "eggTypes",
        labelKey: "EGG_TYPE",
        valueKey: "EGG_TYPE",
        required: true,
      },
      { name: "egg_count", label: "Egg Count", type: "number", required: true },
      {
        name: "trip_no",
        label: "Trip No",
        type: "dropdown_api",
        apiSource: "trips",
        labelKey: "TRIP_NAME",
        valueKey: "TRIP_NAME",
      },
      { name: "comments", label: "Comments", type: "text", required: true },
    ],
  },

  // ─── 4. Egg Sale Summary ──────────────────────────────
  {
    title: "Egg Sale Summary",
    api: "eggSaleSummary",
    fields: [
      {
        name: "sale_date",
        label: "Sale Date",
        type: "date",
        required: true,
      },
      {
        name: "transaction_type",
        label: "Transaction Type",
        type: "dropdown_api",
        apiSource: "eggTransactions",
        labelKey: "TRANSACTION_TYPE",
        valueKey: "TRANSACTION_TYPE",
        required: true,
      },
      {
        name: "egg_type",
        label: "Egg Type",
        type: "dropdown_api",
        apiSource: "eggTypes",
        labelKey: "EGG_TYPE",
        valueKey: "EGG_TYPE",
        required: true,
      },
      {
        name: "eggs_volume",
        label: "Eggs Volume",
        type: "number",
        required: true,
      },
      { name: "gate_pass_no", label: "Gate Pass No", type: "text" },
      {
        name: "customer_name",
        label: "Customer Name",
        type: "text",
        required: true,
      },
      {
        name: "customer_mobile_no",
        label: "Customer Mobile No",
        type: "number",
      },
      {
        name: "transport_mode",
        label: "Transport Mode",
        type: "dropdown",
        options: ["LORRY", "AUTO", "MANUAL", "OTHER"],
      },
      {
        name: "vehicle_type",
        label: "Vehicle Type",
        type: "dropdown",
        options: ["SMALL", "MEDIUM", "LARGE"],
      },
      { name: "vehicle_no", label: "Vehicle No", type: "text" },
      { name: "comments", label: "Comments", type: "text", required: true },
    ],
  },

  // ─── 5. Feed Consumption ──────────────────────────────
  {
    title: "Feed Consumption",
    api: "feedConsumption",
    fields: [
      {
        name: "shed_no",
        label: "Shed",
        type: "dropdown_api",
        apiSource: "sheds",
        labelKey: "SHED_NAME",
        valueKey: "SHED_NAME",
        required: true,
      },
      {
        name: "flock_no",
        label: "Flock",
        type: "dropdown_api",
        apiSource: "flocksByShed",
        labelKey: "FLOCK_NAME",
        valueKey: "FLOCK_NAME",
        dependsOn: "shed_no",
        required: true,
      },
      {
        name: "reporting_date",
        label: "Reporting Date",
        type: "date",
        required: true,
      },
      {
        name: "feed_type",
        label: "Feed Type",
        type: "dropdown_api",
        apiSource: "feeds",
        labelKey: "FEED_TYPE",
        valueKey: "FEED_TYPE",
        required: true,
      },
      { name: "feed_used", label: "Feed Used", type: "number", required: true },
      { name: "comments", label: "Comments", type: "text", required: true },
    ],
  },

  // ─── 6. Feed Production ───────────────────────────────
  {
    title: "Feed Production",
    api: "feedProduction",
    fields: [
      {
        name: "production_date",
        label: "Production Date",
        type: "date",
        required: true,
      },
      {
        name: "feed_type",
        label: "Feed Type",
        type: "dropdown_api",
        apiSource: "feeds",
        labelKey: "FEED_TYPE",
        valueKey: "FEED_TYPE",
        required: true,
      },
      { name: "volume", label: "Volume", type: "number", required: true },
      { name: "category", label: "Category", type: "text" },
      { name: "comments", label: "Comments", type: "text", required: true },
    ],
  },

  // ─── 7. Feed Shed Stock ───────────────────────────────
  {
    title: "Feed Shed Stock",
    api: "feedShedStock",
    fields: [
      {
        name: "shed_no",
        label: "Shed",
        type: "dropdown_api",
        apiSource: "sheds",
        labelKey: "SHED_NAME",
        valueKey: "SHED_NAME",
        required: true,
      },
      {
        name: "flock_no",
        label: "Flock",
        type: "dropdown_api",
        apiSource: "flocksByShed",
        labelKey: "FLOCK_NAME",
        valueKey: "FLOCK_NAME",
        dependsOn: "shed_no",
        required: true,
      },
      {
        name: "reporting_date",
        label: "Reporting Date",
        type: "date",
        required: true,
      },
      {
        name: "feed_type",
        label: "Feed Type",
        type: "dropdown_api",
        apiSource: "feeds",
        labelKey: "FEED_TYPE",
        valueKey: "FEED_TYPE",
        required: true,
      },
      { name: "volume", label: "Volume", type: "number", required: true },
      { name: "comments", label: "Comments", type: "text", required: true },
    ],
  },

  // ─── 8. Feed Supply ───────────────────────────────────
  {
    title: "Feed Supply",
    api: "feedSupply",
    fields: [
      {
        name: "shed_no",
        label: "Shed",
        type: "dropdown_api",
        apiSource: "sheds",
        labelKey: "SHED_NAME",
        valueKey: "SHED_NAME",
        required: true,
      },
      {
        name: "flock_no",
        label: "Flock",
        type: "dropdown_api",
        apiSource: "flocksByShed",
        labelKey: "FLOCK_NAME",
        valueKey: "FLOCK_NAME",
        dependsOn: "shed_no",
        required: true,
      },
      {
        name: "supply_date",
        label: "Supply Date",
        type: "date",
        required: true,
      },
      {
        name: "feed_type",
        label: "Feed Type",
        type: "dropdown_api",
        apiSource: "feeds",
        labelKey: "FEED_TYPE",
        valueKey: "FEED_TYPE",
        required: true,
      },
      { name: "comments", label: "Comments", type: "text", required: true },
    ],
  },

  // ─── 9. Raw Material Stock ────────────────────────────
  {
    title: "Raw Material Stock",
    api: "rawMaterialStock",
    fields: [
      {
        name: "reporting_date",
        label: "Reporting Date",
        type: "date",
        required: true,
      },
      {
        name: "material_type",
        label: "Material Type",
        type: "dropdown",
        options: ["MAIZE", "SOYA", "VITAMINS", "OTHER"],
        required: true,
      },
      { name: "volume", label: "Volume", type: "number", required: true },
      {
        name: "transaction_type",
        label: "Transaction Type",
        type: "dropdown",
        options: ["IN", "OUT", "ADJUSTMENT"],
        required: true,
      },
      { name: "comments", label: "Comments", type: "text", required: true },
    ],
  },

  {
    title: "Shed Egg Production",
    api: "shedEggProduction",
    fields: [
      {
        name: "shed_no",
        label: "Shed",
        type: "dropdown_api",
        apiSource: "sheds",
        labelKey: "SHED_NAME",
        valueKey: "SHED_NAME",
        required: true,
      },
      {
        name: "flock_no",
        label: "Flock",
        type: "dropdown_api",
        apiSource: "flocksByShed",
        labelKey: "FLOCK_NAME",
        valueKey: "FLOCK_NAME",
        dependsOn: "shed_no",
        required: true,
      },
      {
        name: "production_date",
        label: "Production Date",
        type: "date",
        required: true,
      },
      {
        name: "transaction_type",
        label: "Transaction Type",
        type: "dropdown_api",
        apiSource: "eggTransactions",
        labelKey: "TRANSACTION_TYPE",
        valueKey: "TRANSACTION_TYPE",
        required: true,
      },
      {
        name: "egg_type",
        label: "Egg Type",
        type: "dropdown_api",
        apiSource: "eggTypes",
        labelKey: "EGG_TYPE",
        valueKey: "EGG_TYPE",
        required: true,
      },
      { name: "egg_count", label: "Egg Count", type: "number", required: true },
      { name: "batch_no", label: "Batch No", type: "text" },
      { name: "comments", label: "Comments", type: "text", required: true },
    ],
  },
  {
    title: "Shed Feed Received",
    api: "shedFeedReceived",
    fields: [
      {
        name: "shed_no",
        label: "Shed",
        type: "dropdown_api",
        apiSource: "sheds",
        labelKey: "SHED_NAME",
        valueKey: "SHED_NAME",
        required: true,
      },
      {
        name: "flock_no",
        label: "Flock",
        type: "dropdown_api",
        apiSource: "flocksByShed",
        labelKey: "FLOCK_NAME",
        valueKey: "FLOCK_NAME",
        dependsOn: "shed_no",
        required: true,
      },
      {
        name: "reporting_date",
        label: "Reporting Date",
        type: "date",
        required: true,
      },
      {
        name: "feed_type",
        label: "Feed Type",
        type: "dropdown_api",
        apiSource: "feeds",
        labelKey: "FEED_TYPE",
        valueKey: "FEED_TYPE",
        required: true,
      },
      { name: "feed_used", label: "Feed Used", type: "text", required: true },
      {
        name: "feed_balance",
        label: "Feed Balance",
        type: "number",
        required: true,
      },
      { name: "comments", label: "Comments", type: "text", required: true },
    ],
  },
];
